scrape_configs:
  - job_name: 'xunwu-actuator-springboot'
    metrics_path: '/xunwu-order/actuator/prometheus'
    static_configs:
      - targets: ['122.166.0.100:8082']
  - job_name: 'orchestrator-actuator-springboot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['122.166.0.100:10086']
